name: Docker Image CI/CD

on:
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  push_to_registry:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo 
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./bus-reservation-system-in-django/myproject
        push: true
        tags: joel033/bus_booking_system:latest
        
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  selenium_test:
    name: Run Selenium tests
    needs: push_to_registry
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r bus-reservation-system-in-django/myproject/requirements.txt

    - name: Install ChromeDriver
      run: |
        CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
        wget https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip -d /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run tests
      run: python bus-reservation-system-in-django/myproject/manage.py test
      env:
        DJANGO_SETTINGS_MODULE: myproject.settings
